### ISSUE TITLE
☂️ 🐞 Mass disinsection

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/mad-hatter#128]
Umbrella bounty for various small bugfixes

## Scope

- [x] [Payment backend: fix parallel payouts](https://github.com/WhiteRabbitTheWorldIsYours/payment-backend/issues/3) (fixed via https://github.com/WhiteRabbitTheWorldIsYours/payment-backend/pull/9)
- [x] [Subgraph: Unclaimed revenue mismatches Total revenue](https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/73) (fixed via https://github.com/WhiteRabbitTheWorldIsYours/dashboard/pull/101)
- [x] [Dashboard: price query is not working without time window](https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/84) (fixed via https://github.com/WhiteRabbitTheWorldIsYours/dashboard/pull/100)
- [x] [App: check fiat payment is processed by Circle before requesting faucet](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/issues/94) (fixed via https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/131)
- [x] [Dashboard: Common package github build action](https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/63) (fixed via https://github.com/WhiteRabbitTheWorldIsYours/dashboard/pull/102)
## Roles

gardener: @troggy 40 DAI
worker: @troggy 
reviewer: [reviewer]

**Comment by troggy** [comment]
done
